version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/development.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-storage:/app/storage
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - mongodb
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lexarb
      - POSTGRES_PASSWORD=lexarb-password
      - POSTGRES_DB=lexarb

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  mongodb-data:
  redis-data:
  backend-storage: